set showcmd
set showmode
set number

set splitright
set splitbelow

set incsearch
set ignorecase
set hlsearch

set nobackup

set fileformats=unix,dos
set fileformat=unix

set modeline
set modelines=16

set wrap

set laststatus=2
set statusline=%<
set statusline+=%f
set statusline+=\ %h%m%r
set statusline+=%=
set statusline+=%l,%c
set statusline+=\ %P
set statusline+=\ \|
set statusline+=\ %{&fileencoding?&fileencoding:&encoding}
set statusline+=\ %{&fileformat}
set statusline+=%(\ %)

syntax enable
syntax on

filetype on
filetype plugin on
filetype indent on
