#!/usr/bin/env python3

import os
import sys
import subprocess
import json

from pathlib import Path


class Unreachable(Exception):
    pass


def get_args():
    cwd = Path(__file__).resolve().parent

    prog_name = os.path.basename(sys.argv[0])
    args = ["ld"] + sys.argv[1:]

    for x in args:
        if x in ["-v", "--version", "-h", "--help"]:
            return args

        if x == "--mario-verify":
            sys.exit(0)

    flags = ["-m", "elf_i386", "--orphan-handling=warn", "-nostdlib"]
    match prog_name:
        case "ld":
            flags = []

        case "mario-ld":
            pass

        case "mario-libc-ld":
            lib_dir = (cwd / ".." / "libc" / "lib").resolve()
            linker_script = lib_dir / "mario.ld"
            flags.extend(
                [
                    f"-L{lib_dir}",
                    "-lc",
                    "-T",
                    f"{linker_script}",
                ]
            )

        case "mario-musl-ld":
            pass

        case _:
            raise Unreachable()

    args += flags

    for x in args:
        if x.endswith(".c") or x.endswith(".S"):
            with open(f"{x}.compile_command.json", "w", encoding="utf-8") as ofs:
                compile_command = {"directory": os.getcwd(), "command": args, "file": x}
                json.dump(compile_command, ofs)

    return args


def main():
    args = get_args()
    subprocess.run(args, capture_output=False, check=True)


if __name__ == "__main__":
    main()
