#!/usr/bin/env python3

import os
import sys
import subprocess
import json

from pathlib import Path


class Unreachable(Exception):
    pass


def get_libgcc_path():
    cp = subprocess.run(
        ["gcc", "-m32", "-print-libgcc-file-name"],
        check=True,
        capture_output=True,
        encoding="utf-8",
    )
    s = cp.stdout.strip()
    assert s
    return s


def get_gcc_file(name: str):
    name = name.strip()
    assert name and "/" not in name

    cp = subprocess.run(
        ["gcc", "-m32", f"--print-file-name={name}"],
        check=True,
        capture_output=True,
        encoding="utf-8",
    )
    s = cp.stdout.strip()
    assert s.startswith("/")
    return s


def get_args():
    cwd = Path(__file__).resolve().parent

    prog_name = os.path.basename(sys.argv[0])
    args = sys.argv[1:]

    for x in args:
        if x in ["-v", "--version", "-h", "--help"]:
            return args

        if x == "--mario-verify":
            sys.exit(0)

    flags_before = ["-m", "elf_i386"]
    flags = ["--orphan-handling=warn", "-nostdlib"]
    match prog_name:
        case "ld":
            flags = []

        case "mario-ld":
            pass

        case "mario-libc-ld":
            lib_dir = (cwd / ".." / "libc" / "lib").resolve()
            linker_script = lib_dir / "mario.ld"
            flags.extend(
                [
                    f"-L{lib_dir}",
                    "-lc",
                    "-T",
                    f"{linker_script}",
                    f"{get_libgcc_path()}",
                ]
            )

        case "mario-musl-ld":
            musl_dir = (cwd / ".." / "musl").resolve()
            lib_dir = (musl_dir / "musl-1.2.5-install" / "lib").resolve()
            linker_script = musl_dir / "musl.ld"

            flags_before.extend(
                [
                    f'{lib_dir / "crt1.o"}',
                    f'{lib_dir / "crti.o"}',
                    f'{get_gcc_file("crtbegin.o")}',
                ]
            )

            flags.extend(
                [
                    f"-L{lib_dir}",
                    "-lc",
                    "-T",
                    f"{linker_script}",
                    f"{get_libgcc_path()}",
                    f'{get_gcc_file("crtend.o")}',
                    f'{lib_dir / "crtn.o"}',
                    "--gc-sections",
                ]
            )

        case _:
            raise Unreachable()

    args = ["ld"] + flags_before + args + flags
    return args


def main():
    args = get_args()
    subprocess.run(args, capture_output=False, check=True)


if __name__ == "__main__":
    main()
